fruktarine/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

fruktarine/fruktarine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('myapp.urls', namespace='myapp')),  # должен быть последним
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "myapp.views.page_not_found_view"

fruktarine/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
]

fruktarine/myapp/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)  # URL-адрес

    class Meta:  # для изменения поведения полей модели
        ordering = ('name',)  # сортировка
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # возвращаем уникальную ссылку каждый раз, когда обращаемся к методу объекта
        return reverse('myapp:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='Товары')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)  # URL-адрес
    image = models.ImageField(upload_to='products/', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)  # 0 знаков после запятой, для копеек поставить 2
    # stock = models.PositiveIntegerField()  # для хранения остатков данного продукта
    available = models.BooleanField(default=True)  # доступность
    # created = models.DateTimeField(auto_now_add=True)  # дата и время создания
    # updated = models.DateTimeField(auto_now=True)  # дата и время последнего изменения

    """В классе Meta модели Product мы используем параметр мета index_together, чтобы задать индекс для полей id и 
    slug. Мы определим этот индекс, поскольку мы планируем запросить продукты с помощью id и slug. Оба поля 
    индексируются вместе для улучшения представлений для запросов, использующих эти два поля."""
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # возвращаем уникальную ссылку каждый раз, когда обращаемся к методу объекта
        return reverse('myapp:product_detail', args=[self.id, self.slug])

fruktarine/myapp/views.py
import os

from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm  # Убрать/добавить .. чтобы не было ошибок
import json
from django.conf import settings
from rest_framework import serializers


class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = Product
        fields = '__all__'


# def my_view(request):
#     data = MyModelSerializer(Product.objects.all(), many=True).data
#     return JsonResponse(data, safe=False)


def index(request):
    return render(request, 'myapp/base.html')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    # записываем товары в файл json
    json_path = os.path.join('static', 'db', 'products.json')
    json_dict = MyModelSerializer(products, many=True).data
    with open(json_path, 'w') as f_json:
        json.dump({'products': json_dict}, f_json, indent=2)
    return render(request,
                  'myapp/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'myapp/product/detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})


def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

fruktarine/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}

<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Экзотические фрукты в Уфе{% endblock %}</title>
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
  />

  <link rel="stylesheet" href="{% static "css/style.css" %}">
  <meta name="description" content="">

  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">
  <meta property="og:image:alt" content="">

  <link rel="icon" href="{% static "img/mango.png" %}" sizes="any">
  <link rel="icon" href="{% static "img/mango.svg" %}" type="image/svg+xml">
  <link rel="apple-touch-icon" href="{% static "img/mango.png" %}">

  <link rel="manifest" href="{% static "site.webmanifest" %}">
  <link rel="stylesheet" href="https://use.typekit.net/pbh8rbz.css">
  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
</head>

<body>

<header class="top-bar" id="top-bar">
  <nav class="nav center">
    <button class="btn-reset burger" id="burger-btn">
      <span class="burger__line"></span>
      <span class="burger__line"></span>
      <span class="burger__line"></span>
    </button>
    <div class="nav__right">
      <a href="https://vk.com/fruktarine_ufa" class="margin__right-5 vk-logo-box"><img src="{% static "img/vk_logo.svg" %}"
                                                                                       alt="Логотип Вконтакте переход на страницу"></a>
      <span class="phone-number">+7 987 039–19–49</span>
      <button class="btn-reset btn-basic full-height" type="button">Заказать звонок</button>
      <a href="{% url "cart:cart_detail" %}" class="btn-reset btn-cart__top margin__left-1-2rem">
        <svg class="btn-cart__top_img" width="20" height="20" fill="none" viewBox="0 0 34 33"
             xmlns="http://www.w3.org/2000/svg">
          <path
            d="M1 0C0.447715 0 0 0.447715 0 1C0 1.55228 0.447715 2 1 2H5.59274C6.0537 2 6.45495 2.3151 6.56423 2.76293L11.2125 21.8106C11.5403 23.154 12.744 24.0993 14.1269 24.0993H28.0527C28.6049 24.0993 29.0527 23.6516 29.0527 23.0993C29.0527 22.5471 28.6049 22.0993 28.0527 22.0993H14.1269C13.666 22.0993 13.2647 21.7842 13.1554 21.3364L12.4376 18.395H29.0371C29.9273 18.395 30.7104 17.8066 30.9581 16.9515L33.5902 7.86552C33.9608 6.5863 33.001 5.30902 31.6692 5.30902H9.88892C9.67084 5.30902 9.46242 5.3434 9.26806 5.40659L8.50721 2.28878C8.17936 0.945304 6.97564 0 5.59274 0H1Z"
            fill="#869FA6"/>
          <path
            d="M15.8599 29.9578C15.8599 31.6412 14.4952 33.006 12.8117 33.006C11.1283 33.006 9.76353 31.6412 9.76353 29.9578C9.76353 28.2743 11.1283 26.9096 12.8117 26.9096C14.4952 26.9096 15.8599 28.2743 15.8599 29.9578Z"
            fill="#869FA6"/>
          <path
            d="M32.6249 29.9578C32.6249 31.6412 31.2602 33.006 29.5767 33.006C27.8933 33.006 26.5286 31.6412 26.5286 29.9578C26.5286 28.2743 27.8933 26.9096 29.5767 26.9096C31.2602 26.9096 32.6249 28.2743 32.6249 29.9578Z"
            fill="#869FA6"/>
        </svg>
        <span class="cart__count">{{ cart|length }}</span>
      </a>
    </div>
  </nav>

  <nav class="burger__menu" id="burger-menu">
    <ul class="center margin__top-1-2rem">
      <li class="burger__item"><a class="menu-link" href="{% url "myapp:product_list"%}#product-gallery">Витрина фруктовых корзин</a></li>
      <li class="burger__item"><a class="menu-link" href="{% url "myapp:product_list"%}#delivery">Условия доставки и оплаты</a></li>
      <li class="burger__item"><a class="menu-link" href="{% url "myapp:product_list"%}#contacts">Контакты</a></li>
    </ul>
  </nav>
</header>


<div id="content">
    {% block content %}
    {% endblock %}
</div>

<footer class="footer center">
  <p class="footer__credits">© Все права защищены. ОГРН 321028000080939  ИНН 027302483046  г. Уфа Пр. Октября 40/1</p>
</footer>

<script src="{% static "js/app.js" %}"></script>
</body>
</html>